var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/poetry/[slug]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__057amb9._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0gbjiqx.js")
R.c("server/chunks/ssr/node_modules_0bdw-d.._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0i_._k3._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0puqpif._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ep_oo._.js")
R.c("server/chunks/ssr/src_app_not-found_0h_fv8i.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/src_app_poetry_[slug]_layout_0kmhr9n.js")
R.c("server/chunks/ssr/_next-internal_server_app_poetry_[slug]_page_actions_06veyo..js")
R.m(51462)
module.exports=R.m(51462).exports
