var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/admin/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__07dr928._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0i_._k3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0n~dlww.js")
R.c("server/chunks/ssr/[root-of-the-server]__0puqpif._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ep_oo._.js")
R.c("server/chunks/ssr/src_app_not-found_0h_fv8i.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_admin_page_actions_0ycnu8f.js")
R.m(75297)
module.exports=R.m(75297).exports
