var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0-a6z3t._.js")
R.c("server/chunks/ssr/src_0.t4yem._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0i_._k3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_13e3~~s.js")
R.c("server/chunks/ssr/[root-of-the-server]__0puqpif._.js")
R.c("server/chunks/ssr/node_modules_next_dist_03nkrli._.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ep_oo._.js")
R.c("server/chunks/ssr/src_app_not-found_0h_fv8i.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0ee1czk._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_09-gtaw.js")
R.m(33877)
module.exports=R.m(33877).exports
